# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lyrics', models.CharField(max_length=300, null=True)),
                ('artist', models.CharField(max_length=120)),
                ('content', models.TextField(max_length=6000)),
                ('image', models.ImageField(blank=True, upload_to=posts.models.location)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
