# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='Enter your content here', max_length=6000),
            preserve_default=False,
        ),
    ]
